# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('hausNumber', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
