# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('hous_number', models.CharField(max_length=15)),
                ('place_pic', models.FileField(blank=True, upload_to='place_pic')),
            ],
        ),
    ]
