# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ballerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='adresse',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
