# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballerapp', '0007_auto_20170413_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
