# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballerapp', '0008_userprofile_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='hausNumber',
            new_name='hous_number',
        ),
        migrations.AddField(
            model_name='adresse',
            name='place_pic',
            field=models.ImageField(blank=True, upload_to='place_pic'),
        ),
    ]
